name: who_am_i
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  path: ^1.8.0
  speech_to_text: ^7.0.0
  cupertino_icons: ^1.0.8
  sensors_plus: ^6.1.0
  confetti: ^0.8.0
  path_provider_windows: ^2.1.0 
  open_file: ^3.5.10
  image_picker: ^0.8.7+4
  path_provider: ^2.0.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true